Add missing implementation of LOCAL-ADDR for CCL
Previously, starting up a Swank server on CCL would jump you into the
debugger:

    > Error: SWANK/BACKEND:LOCAL-ADDR not implemented
    > While executing: SWANK/BACKEND:LOCAL-ADDR, in process listener(1).
    > Type :GO to continue, :POP to abort, :R for a list of available restarts.
    > If continued: Skip loading "/Users/matteolandi/.lisp/vlime-lswank.lisp"
    > Type :? for other options.

This commit adds the missing implementation, and with this, it's
possible to start a Swank server on CCL just fine.